mysql:
        image: mariadb
        environment:
            - "MYSQL_ROOT_PASSWORD=secret"
            - "MYSQL_USER=app"
            - "MYSQL_PASSWORD=secret"
            - "MYSQL_DATABASE=db"
        ports:
            - "33062:3306"
        volumes:
          - ./mysql-data:/var/lib/mysql
