mysql:
        image: mysql:5.7
        environment:
            - "MYSQL_ROOT_PASSWORD=secret"
            - "MYSQL_USER=app"
            - "MYSQL_PASSWORD=secret"
            - "MYSQL_DATABASE=db"
        ports:
            - "33061:3306"
        volumes:
          - ~/var/lib/mysql-docker:/var/lib/mysql
